apiVersion: v1
kind: Service
metadata:
  name: "factorial-service"
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 9081
  - name: https
    port: 9444

  selector:
    app: "factorial-selector"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "factorial-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "factorial-selector"
    spec:
      containers:
      - name: factorial
        image: factorial:latest
        imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
